### ISSUE TITLE
variable hue isn't declared

### ISSUE THREAD

**Issue by dbaileydev** [blaringsilence/flat-color-generator#2]
After implementing the code into my codebase for my project I noticed an error that resulted from the "hue" variable not being initialized. 

After adding `var hue;` underneath the previous declared variables the program worked perfectly. 

Hope this helps! Thanks again for the help!

**Comment by mariamrf** [comment]
Solved with ca1a474a8bdd3e137267d4479018b67d5a9d8e41.
